// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

import {
  getAuth,
  signInWithRedirect,
  signInWithPopup,
  GoogleAuthProvider,
} from "firebase/auth";

// Your web app's Firebase configuration
const firebaseConfig = {
  apiKey: "AIzaSyBdEVE4TInhcJ8uRDuIemlOApVZaMcODUs",
  authDomain: "crwn-clothing-db-1560c.firebaseapp.com",
  projectId: "crwn-clothing-db-1560c",
  storageBucket: "crwn-clothing-db-1560c.firebasestorage.app",
  messagingSenderId: "1056643990819",
  appId: "1:1056643990819:web:24e9d55d868b8fea56f896",
};

// Initialize Firebase
const firebaseApp = initializeApp(firebaseConfig);

//above is the code generated by my webapp in the firebase project
//how to get it
//create project in the firebase
//then create webapp in it
//click the </> sign
//name and register the webapp
//and u will get the above code
//what it does is imports the iniApp and inis it with the config file customized to our project
//also imports other essential things that we might need in the course of our project

// the below part is for google authentication
// like wise i can put other auths as well like gh, twitter, fb, ....
// const facebookProvider = new FacebookAuthProvider();
// const githubProvider = new GithubAuthProvider();
const provider = new GoogleAuthProvider();

// this is a custom setting to the above inid provider
// which tells to display select account no matter if the user is logged in or not
// for safety, in case using rbrowser with multiple accounts logins
provider.setCustomParameters({
  prompt: "select_account",
});

//initializing the authentication
export const auth = getAuth();

//this function when called, opens google sign -in as pop up
//both above inid auth and provider go into this
export const signInWithGooglePopup = () => signInWithPopup(auth, provider);

// the create user code below is incomplete.
// it is basically meant to store info into the db or firestore after authentication?
export const createUserProfileDocument = async (userAuth, additionalData) => {
  //if userAuth is empty in first place
  //not that there is no this kind of userAuth in the DB
  if (!userAuth) return;

  console.log(userAuth);
};
